project:
  type: website

website:
  title: "Kayla Schroeder"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research_projects.qmd
        text: Projects
      - href: CV/CV_Kayla_Schroeder_v3.pdf
        text: CV
  page-footer: 
    background: light
    left: 
      - "Copyright 2023, Kayla Schroeder"

format:
  html:
    theme: 
      - stylesheet1.scss
    mainfont: Montserrat
    toc: true

editor: source


