project:
  type: website

website:
  title: "Kayla Schroeder"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: CV/CV_Kayla_Schroeder.pdf
        text: CV

format:
  html:
    css: styles.css
    toc: true

editor: source


